language: node_js
matrix:
  fast_finish: true
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
- yarn test
- yarn build:css:all
- yarn build:doc:react
- yarn screenshots
- yarn argos --token $ARGOS_TOKEN --branch $TRAVIS_BRANCH --commit $TRAVIS_COMMIT
after_success:
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_REPO_SLUG = "cozy/cozy-ui" && test $TRAVIS_PULL_REQUEST = "false" && yarn
  build:doc:kss && yarn deploy:doc -- --username cozycloud --email contact@cozycloud.cc
  --repo=https://$GITHUB_TOKEN@github.com/cozy/cozy-ui.git
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_REPO_SLUG = "cozy/cozy-ui" && yarn travis-deploy-once "yarn semantic-release"

env:
  global:
  # GH_TOKEN from cozy-bot (readable from password-store/cozy-ui/github-token-for-semantic-release-on-travis)
  - secure: fMlsp52RBxJCGqB1cR5ShG3WiGl2iTl3cvzskrFqWIxrpOFc0TBaSQmpiOdkc9lg35zt8Pt1Z9F8zlWX/k/SXcR0x5SwSzunVXl1P/FzZkJ1pjtG3pVw5gtlhhuSfMhtu/cUSNyil0CfTvWbhSSkdeBpaR+J9TapBKH6qvIYGo4=
