language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
after_success:
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_REPO_SLUG = "cozy/cozy-ui" && yarn build:doc && yarn deploy:doc --username cozycloud --email contact@cozycloud.cc
deploy:
  provider: npm
  email: npm@cozycloud.cc
  api_key:
    secure: eAJXf3L6DM6HNPzHs27PquK/HVIfE0T+lsM/7E6pFu5dL3q0X6A7cPE0bZ8U1VES+gie3HVxcTcNRG1sCkZJE85kqOhqj8IkFvzfD//5jObhET6JauA7xHUBR5JDhYmPNmrixGpIZpgCkc2UTmgngUQxY0zvQWtImZkgLtvzb5Q=
  on:
    tags: true
    repo: cozy/cozy-ui
env:
  global:
    secure: PHiyG4tAClhkEozcVAJH9j27+RBOJ7qGHGC5eXUJADa6pT2VLqKOwERIgoma4nTMzK+Le3E3aIhKOyjj9jlbhPKutu6w8AZLGNrtB8xDjQqYOOqlehjGdk+L/iAjPxiDAYZtEsnmZdmFMDgyPxaxc/yzt74zsajNhlRvlfkWABk=
